first:
    resource: "@firstBundle/Resources/config/routing.yml"
    prefix:   /

plop:
    resource: "@PlopBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: @AppBundle/Controller/
    type:     annotation
