first_homepage:
    path:     /
    defaults: { _controller: firstBundle:Default:index }

first_contact:
    path:     /contact
    defaults: { _controller: firstBundle:Default:contact }

first_event:
    path:     /event
    defaults: { _controller: firstBundle:Default:event }

first_infos:
    path:     /infos
    defaults: { _controller: firstBundle:Default:infos }

first_rules:
    path:     /rules
    defaults: { _controller: firstBundle:Default:rules }

